# Site settings
title: sudhanshuthakurr 
description: Portfolio 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sudhanshu Singh
user_description: I’m Currently Pursuing Bachelors In Computer & Science Engineering From HBTI K,I've decided to be part of the ecological transition , My current Aim is to work in a good and challenging envoirnment that will let me apply my technical skills in a professional manner. I want to get involved in social work along with my profession. 
user_title: Entrepreneur-Developer
email: sudhanshuthakurr123@gmail.com
github_username: sudhanshuthakurr
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
